-- ۱) بایگانی سابقه‌ی احراز هویت: تریگر قبلی ردیف‌های قبلی هر کاربر را پاک می‌کرد و سابقه از بین می‌رفت
CREATE TABLE IF NOT EXISTS public.identity_verifications_archive (LIKE public.identity_verifications INCLUDING DEFAULTS);
ALTER TABLE public.identity_verifications_archive ADD COLUMN IF NOT EXISTS archived_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.identity_verifications_archive ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS identity_archive_admin_select ON public.identity_verifications_archive;
CREATE POLICY identity_archive_admin_select ON public.identity_verifications_archive FOR SELECT
  USING (private.is_admin_or_super((auth.jwt() ->> 'email')));

CREATE OR REPLACE FUNCTION public.identity_verifications_replace_previous()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.identity_verifications_archive
  select v.*, now() from public.identity_verifications v where v.email = new.email;
  delete from public.identity_verifications where email = new.email;
  return new;
end;
$function$;

-- ۲) ثبت خطاهای اپ (لاگ Supabase فقط چند ساعت نگه داشته می‌شود)
CREATE TABLE IF NOT EXISTS public.client_errors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  email text,
  app text,
  context text,
  message text CHECK (message IS NULL OR length(message) <= 2000),
  detail jsonb,
  user_agent text CHECK (user_agent IS NULL OR length(user_agent) <= 500)
);
ALTER TABLE public.client_errors ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS client_errors_insert_own ON public.client_errors;
CREATE POLICY client_errors_insert_own ON public.client_errors FOR INSERT TO authenticated
  WITH CHECK (email = (auth.jwt() ->> 'email'));
DROP POLICY IF EXISTS client_errors_admin_select ON public.client_errors;
CREATE POLICY client_errors_admin_select ON public.client_errors FOR SELECT
  USING (private.is_admin_or_super((auth.jwt() ->> 'email')));
CREATE INDEX IF NOT EXISTS client_errors_created_at_idx ON public.client_errors (created_at DESC);
